// ProductService for Ecwid API

import {Ecwid} from "ecwid-api-client";
import type { CategoriesResponse } from '@/types/categories.types'
import { ecwidConfig } from '@/constants/ecwid'


const ecwid = new Ecwid(ecwidConfig);

export const ApiService = {
  getCategories: async () => {
    const fields = [
      'id',
      'name',
      'thumbnailUrl',
      'alt',
      'autogeneratedSlug'
    ]
    const responseFields = fields.join(',')
    return ecwid.api.getRequest<CategoriesResponse>(`/categories?responseFields=items(${responseFields})`)
  },
  getProducts: async (keyword: string = '') => {
    return ecwid.products.getByKeyword(keyword);
  },
  getProduct: async (productId: number) => {
    return ecwid.products.getById(productId);
  }
}
