import { Ecwid, type SearchResult } from 'ecwid-api-client'
import type { CategoriesResponse } from '@/types/types'
import { ecwidConfig } from '@/constants/ecwid'
import type { RichProduct } from '@/types/types'

const ecwid = new Ecwid(ecwidConfig)

export const ApiService = {
  getCategories: async () => {
    const fields = ['id', 'name', 'thumbnailUrl', 'alt', 'autogeneratedSlug']
    const responseFields = fields.join(',')
    return ecwid.api.getRequest<CategoriesResponse>(
      `/categories?responseFields=items(${responseFields})`
    )
  },
  getProducts: async (keyword: string = ''): Promise<SearchResult<RichProduct>> => {
    return ecwid.products.getByKeyword(keyword) as Promise<SearchResult<RichProduct>>
  },

  getProduct: async (productId: number) => {
    return ecwid.products.getById(productId) as Promise<RichProduct>
  }
}
