<template>
  <!-- Categories Section -->
  <section class="mb-8" id="categories">
    <h2 class="text-2xl font-bold mb-2">Categories</h2>
    <div class="flex flex-wrap flex-row gap-4">
      <RouterLink
        v-for="category in categories.items"
        :key="category.id"
        :to="getToForCategory(category.autogeneratedSlug)"
        class="bg-white p-4 rounded-lg shadow-md flex flex-col items-center justify-center transition duration-300 ease-in-out transform hover:scale-105 hover:bg-emerald-50"
      >
        <img
          :src="category.thumbnailUrl"
          :alt="category.name"
          class="w-24 h-24 object-cover rounded-full mb-2"
        />
        <span class="text-lg font-semibold">{{ category.name }}</span>
      </RouterLink>
    </div>
  </section>

  <!-- Products Section -->
  <section>
    <h2 class="text-2xl font-bold mb-2 flex flex-row gap-4 items-baseline">
      Products
      <span v-if="isLoading" class="text-gray-600">
        <LoaderIcon size="6" color="text-emerald-400"/>
      </span>
    </h2>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
      <RouterLink
        :to="productToLink(product)"
        v-for="product in products.items"
        :key="product.id"
        class="bg-white p-4 rounded-lg shadow-md flex flex-col items-center justify-center transition duration-300 ease-in-out transform hover:bg-emerald-50 gap-1"
      >
        <img
          :src="product.thumbnailUrl"
          :alt="product.name"
          class="w-32 h-32 object-contain mb-2"
        />
        <span class="text-lg font-semibold">{{ product.name }}</span>
        <span class="text-gray-600">{{ formatPrice(product.price) }}</span>
        <AddToCartButton :product="product" />
      </RouterLink>
    </div>
  </section>
</template>

<script lang="ts">
import { useRoute } from 'vue-router'

import { computed, defineComponent, onMounted, ref, watch } from 'vue'
import { useStoreStore } from '@/stores/store'
import { storeToRefs } from 'pinia'
import { useCartStore } from '@/stores/cart'
import { formatPrice, productToLink } from '@/utils/client'
import type { CategoriesItem, RichProduct } from '@/types/types'
import AddToCartButton from '@/components/AddToCartButton.vue'
import LoaderIcon from '@/components/LoaderIcon.vue'

export default defineComponent({
  components: { LoaderIcon, AddToCartButton },
  methods: { formatPrice, productToLink },
  setup() {
    const isLoading = ref(true)
    const route = useRoute()
    const store = useStoreStore()
    const { categories, products } = storeToRefs(store)

    const selectedCategorySlug = computed(() => route.params.categorySlug)

    watch(selectedCategorySlug, async () => {
      await loadPage()
    })

    const loadPage = async () => {
      isLoading.value = true
      if (categories.value.items.length === 0) {
        await store.loadCategories()
      }

      const selectedCategory = categories.value.items.find((category: CategoriesItem) => {
        return category.autogeneratedSlug === selectedCategorySlug.value
      })

      await store.loadProducts(selectedCategory?.name || '')
      isLoading.value = false
    }

    const getToForCategory = (categorySlug: string) => {
      return { name: 'category', params: { categorySlug: categorySlug } }
    }

    onMounted(loadPage)

    const addToCart = (product: RichProduct) => {
      const cart = useCartStore()
      cart.addItem(product)
    }

    return {
      categories,
      products,
      addToCart,
      getToForCategory,
      isLoading
    }
  }
})
</script>

<style scoped>
#categories .router-link-active {
  background-color: lightgoldenrodyellow;
}
</style>
